apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game
  name: runaway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - image: hanansalem88/runway:latest
        name: game
        ports:
        - containerPort: 80
          name: game