apiVersion: v1
kind: Service
metadata:
  labels:
    app: game
  name: game-run
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: game