apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: mydeployment
    kind: frontend
spec:
  template:
    metadata:
      name: my-first-game
      labels:
        app: myFirstgame
        type: frontend
    spec:
      containers:
        - name: dojo-jump
          image: hanansalem88/dojo-jump
  selector:
    matchLabels:
      type: frontend