apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: mydeployment
    type: frontend
spec:
  selector:
    matchLabels:
      app: mydeployment
  template:
    metadata:
      name: my-first-game
      labels:
        app: mydeployment
        type: frontend
    spec:
      containers:
        - name: dojo-jump
          image: hanansalem88/dojo-jump
          ports:
            - containerPort: 80
              name: mydeployment
