apiVersion: v1
kind: Service
metadata:
  name: game-service
  labels:
    app: game-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 
      targetPort: 8080 
      nodePort: 30000
      protocol: TCP
  selector:
      type: frontend