apiVersion: v1
kind: Service
metadata:
  name: game-svc
  labels:
    app: game-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 
      targetPort: 80 
      nodePort: 31089 
      protocol: TCP
  selector:
    matchLabels:
        app: myFirstgame
        type: frontend
  