apiVersion: v1
kind: Service
metadata:
  name: game-service
  labels:
    app: ame-service
spec:
  type: NodePort
  ports: 
    - name: http
      port: 80 
      targetPort: 80 
      nodePort: 32000
  selector:
    matchLabels:
      app: myFirstgame
      type: frontend
  